import dotenv from "dotenv";

dotenv.config();

const Gemini_URL =
    "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent";



export const generateGeminiResponse = async (prompt) => {

    try {


        const response = await fetch(
            `${Gemini_URL}?key=${process.env.GEMINI_API_KEY}`,
            {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({

                    contents: [
                        {
                            parts: [
                                {
                                    text: prompt
                                }
                            ]
                        }
                    ]

                })
            }
        );
        // Check API response status
        if (!response.ok) {

            const errorMessage = await response.text();
            throw new Error(
                `Gemini API Error: ${errorMessage}`
            );
        }
        // Convert response into JSON
        const data = await response.json();
        // Extract AI generated text
        const text =
            data
                ?.candidates?.[0]
                ?.content
                ?.parts?.[0]
                ?.text;
        // Check empty response
        if (!text) {

            throw new Error(
                "No response generated by Gemini"
            );

        }
        // Clean markdown formatting
        const cleanText = text
            .replace(/```json/g, "")
            .replace(/```javascript/g, "")
            .replace(/```/g, "")
            .trim();

        return JSON.parse(cleanText);

    } catch (error) {

        console.error(
            "Gemini Service Error:",
            error.message
        );

        throw error;
    }
};
